### ISSUE TITLE
errors and outdated fmstudio versions

### ISSUE THREAD

**Issue by tuleo1** [pixelomer/Celeste-ARM64#1]
fmodstudio has been updated to 20204 version rather than 20202 which does makes a lot of compatibility issues, but other than that.
I'm getting an error of 
"The entry point method could not be loaded due to Could not load file or assembly 'Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553' or one of its dependencies."
I did install everything made sure to copy the fmod libs to the lib64 in the Celeste folder and everything but when I do run ./Celeste I get that error, I did try to run it with mono Celeste.exe as well but I do get the same error, do I need to install anything or have I done something wrong in the installation and or patching process?

**Comment by pixelomer** [comment]
You can still download version 2.02.02 by selecting it from the dropdown menu in the download page. Version 2.02.04 will not work with the patcher until it is updated. As for the error, you might have accidentally deleted a DLL file from the game file. Could you try downloading the game again and comparing the DLL files?

**Comment by pixelomer** [comment]
You can still download version 2.02.02 by selecting it from the dropdown menu in the download page. Version 2.02.04 will not work with the patcher until it is updated. As for the error, you might have accidentally deleted a DLL file from the game file. Could you try downloading the game again and comparing the DLL files?

**Comment by tuleo1** [comment]
> You can still download version 2.02.02 by selecting it from the dropdown menu in the download page. Version 2.02.04 will not work with the patcher until it is updated. As for the error, you might have accidentally deleted a DLL file from the game file. Could you try downloading the game again and comparing the DLL files?

oh yeah this is probably cuz I tried downloading and using the steam unlocked version, and that was the windows version without the .dll files that the Linux version has (mainly fna.dll files) but then again I can't be sure exactly, since I can't access the fna.dll files to actually test if it works now so I can't check, but thank you for your reply!
