### ISSUE TITLE
Temporary Fmod Account And Mail Creation Failed On Nintendo Switch - Ubuntu Bionic

### ISSUE THREAD

**Issue by lori2012real** [pixelomer/Celeste-ARM64#21]
when i run the script on a terminal on linux it says missing otherlibs/makefile, skipping
missing fmod/makefile, skipping
patching celeste.exe
creating launch script
downloading libfmod
creating temporary email... ./download-fmod.sh: line 16: curl: command not found
creating fmod.com account... ./download-fmod.sh: line 16: curl: command not found
(i copied the error log manually by reading it)
any help?

**Comment by pixelomer** [comment]
It seems like you're missing some dependencies. You can install them with the following command:

    sudo apt-get install -y jq curl

**Comment by lori2012real** [comment]
> curl

Thanks! It Worked! :)

**Comment by lori2012real** [comment]
> It seems like you're missing some dependencies. You can install them with the following command:
> 
> ```
> sudo apt-get install -y jq curl
> ```

I'm Writing Here So That i Don't Open a New Issue. Basically Celeste Opens Fine And Works On Linux, Olympus Crashes a Lot Though (still on linux) I Can't Install Everest, I Tried On Windows And Ministaller Failed, iTried On Windows After Patching With Arm64 And It Failed, I Tried Both Ways On Linux Too And It Failed. How Do i Fix It? Thanks! 👍🏻

**Comment by lori2012real** [comment]
Hey, i got another problem :/ Basically Celeste Opens Fine And Works On Linux, Olympus Crashes a Lot Though (still on linux) I Can't Install Everest, Ministaller Fails. And Olympus Doesn't Evrn Generate Any Log! I Tried On Windows And Ministaller Failed, iTried On Windows After Patching With Arm64 And It Failed, I Tried Both Ways On Linux Too And It Failed. How Do i Fix It? Thanks! 👍🏻
